from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileSystemModel
from functools import partial
import numpy as np
import genbank as genbank

class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(1173, 822)
                MainWindow.setStyleSheet("")
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
                self.centralwidget.setSizePolicy(sizePolicy)
                self.centralwidget.setObjectName("centralwidget")

                # background graphic view
                self.mainGraphicView = QtWidgets.QGraphicsView(self.centralwidget)
                self.mainGraphicView.setGeometry(QtCore.QRect(0, -100, 1171, 881))
                self.mainGraphicView.setStyleSheet("background-color: rgb(245, 250, 255);\n"
        "color: rgb(7, 32, 51);")
                self.mainGraphicView.setObjectName("mainGraphicView")


                self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
                self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 110, 1171, 671))
                self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")

                # container
                self.container = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
                self.container.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
                self.container.setContentsMargins(40, 10, 40, 40)
                self.container.setSpacing(40)
                self.container.setObjectName("container")

                # left container (partie arborescence)
                self.left_container = QtWidgets.QVBoxLayout()
                self.left_container.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
                self.left_container.setContentsMargins(-1, 0, -1, -1)
                self.left_container.setSpacing(8)
                self.left_container.setObjectName("left_container")

                # label "arborescence"
                self.labelArborescence = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
                self.labelArborescence.setEnabled(True)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.labelArborescence.sizePolicy().hasHeightForWidth())
                self.labelArborescence.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setFamily("Ubuntu Condensed")
                font.setPointSize(25)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.labelArborescence.setFont(font)
                self.labelArborescence.setStyleSheet("font: 25pt \"Ubuntu Condensed\";\n" "")
                self.labelArborescence.setAlignment(QtCore.Qt.AlignCenter)
                self.labelArborescence.setObjectName("labelArborescence")
                self.left_container.addWidget(self.labelArborescence)
                
                # container légende ( code couleurs arborescence )
                self.legende_container = QtWidgets.QHBoxLayout()
                self.legende_container.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
                self.legende_container.setContentsMargins(10, 10, 10, 10)
                self.legende_container.setSpacing(8)
                self.legende_container.setObjectName("legende_container")
                self.graphicViewActualise = QtWidgets.QGraphicsView(self.horizontalLayoutWidget_2)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(10)
                sizePolicy.setVerticalStretch(10)
                sizePolicy.setHeightForWidth(self.graphicViewActualise.sizePolicy().hasHeightForWidth())

                # code couleur fichier actualisé
                self.graphicViewActualise.setSizePolicy(sizePolicy)
                self.graphicViewActualise.setMaximumSize(QtCore.QSize(30, 30))
                self.graphicViewActualise.setObjectName("graphicViewActualise")
                self.legende_container.addWidget(self.graphicViewActualise)
                self.labelActualise = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.labelActualise.sizePolicy().hasHeightForWidth())
                self.labelActualise.setSizePolicy(sizePolicy)
                self.labelActualise.setStyleSheet("")
                self.labelActualise.setAlignment(QtCore.Qt.AlignCenter)
                self.labelActualise.setObjectName("labelActualise")
                self.legende_container.addWidget(self.labelActualise)

                #code couleur fichier créé
                self.graphicViewCree = QtWidgets.QGraphicsView(self.horizontalLayoutWidget_2)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(10)
                sizePolicy.setVerticalStretch(10)
                sizePolicy.setHeightForWidth(self.graphicViewCree.sizePolicy().hasHeightForWidth())
                self.graphicViewCree.setSizePolicy(sizePolicy)
                self.graphicViewCree.setMaximumSize(QtCore.QSize(30, 30))
                self.graphicViewCree.setObjectName("graphicViewCree")
                self.legende_container.addWidget(self.graphicViewCree)
                self.labelCree = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.labelCree.sizePolicy().hasHeightForWidth())
                self.labelCree.setSizePolicy(sizePolicy)
                self.labelCree.setStyleSheet("")
                self.labelCree.setAlignment(QtCore.Qt.AlignCenter)
                self.labelCree.setObjectName("labelCree")
                self.legende_container.addWidget(self.labelCree)

                #code couleur fichier supprimé
                self.graphicViewSupprime = QtWidgets.QGraphicsView(self.horizontalLayoutWidget_2)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(10)
                sizePolicy.setVerticalStretch(10)
                sizePolicy.setHeightForWidth(self.graphicViewSupprime.sizePolicy().hasHeightForWidth())
                self.graphicViewSupprime.setSizePolicy(sizePolicy)
                self.graphicViewSupprime.setMaximumSize(QtCore.QSize(30, 30))
                self.graphicViewSupprime.setObjectName("graphicViewSupprime")
                self.legende_container.addWidget(self.graphicViewSupprime)
                self.labelSupprime = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.labelSupprime.sizePolicy().hasHeightForWidth())
                self.labelSupprime.setSizePolicy(sizePolicy)
                self.labelSupprime.setStyleSheet("")
                self.labelSupprime.setAlignment(QtCore.Qt.AlignCenter)
                self.labelSupprime.setObjectName("labelSupprime")
                self.legende_container.addWidget(self.labelSupprime)
                self.left_container.addLayout(self.legende_container)

                # layout arborescence
                self.layout_for_tree = QtWidgets.QVBoxLayout()
                self.layout_for_tree.setObjectName("layout_for_tree")

                self.model = QFileSystemModel()
                self.model.setRootPath("./Results/Eukaryota")
                
                # tree View
                self.treeView = QtWidgets.QTreeView(self.horizontalLayoutWidget_2)
                
                self.treeView.setModel(self.model)
                self.treeView.setRootIndex(self.model.index("./Results"))
                self.treeView.setObjectName("treeView")
                self.treeView.setAnimated(False)
                self.treeView.setSortingEnabled(True)
                self.treeView.setWindowTitle("Results")

                self.layout_for_tree.addWidget(self.treeView)
                self.left_container.addLayout(self.layout_for_tree)

                # bar de progression
                self.progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget_2)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
                self.progressBar.setSizePolicy(sizePolicy)
                self.progressBar.setStyleSheet("color: rgb(7, 32, 51);")
                self.progressBar.setProperty("value", 24)
                self.progressBar.setObjectName("progressBar")
                self.left_container.addWidget(self.progressBar)

                # container boutons de contrôle
                self.buttons_container = QtWidgets.QHBoxLayout()
                self.buttons_container.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
                self.buttons_container.setContentsMargins(-1, 10, -1, 10)
                self.buttons_container.setObjectName("buttons_container")

                # bouton start
                self.buttonStart = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.buttonStart.sizePolicy().hasHeightForWidth())
                self.buttonStart.setSizePolicy(sizePolicy)
                self.buttonStart.setStyleSheet("color: rgb(7, 32, 51);")
                self.buttonStart.setObjectName("buttonStart")
                self.buttons_container.addWidget(self.buttonStart)

                #bouton stop
                self.buttonStop = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.buttonStop.sizePolicy().hasHeightForWidth())
                self.buttonStop.setSizePolicy(sizePolicy)
                self.buttonStop.setStyleSheet("color: rgb(7, 32, 51);")
                self.buttonStop.setObjectName("buttonStop")
                self.buttons_container.addWidget(self.buttonStop)

                # bouton reset
                self.buttonReset = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.buttonReset.sizePolicy().hasHeightForWidth())
                self.buttonReset.setSizePolicy(sizePolicy)
                self.buttonReset.setStyleSheet("color: rgb(7, 32, 51);")
                self.buttonReset.setObjectName("buttonReset")
                self.buttons_container.addWidget(self.buttonReset)

                # connecter les boutons aux fonctions

                


                # container de gauche (menu et log)
                self.left_container.addLayout(self.buttons_container)
                self.left_container.setStretch(0, 2)
                self.left_container.setStretch(2, 18)
                self.left_container.setStretch(3, 1)
                self.left_container.setStretch(4, 1)
                self.container.addLayout(self.left_container)
                self.right_container = QtWidgets.QVBoxLayout()
                self.right_container.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
                self.right_container.setContentsMargins(-1, -1, -1, 0)
                self.right_container.setObjectName("right_container")
                self.labelPreferences = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.labelPreferences.sizePolicy().hasHeightForWidth())
                self.labelPreferences.setSizePolicy(sizePolicy)
                self.labelPreferences.setStyleSheet("font: 75 25pt \"Ubuntu Mono\";\n""")
                self.labelPreferences.setAlignment(QtCore.Qt.AlignCenter)
                self.labelPreferences.setObjectName("labelPreferences")
                self.right_container.addWidget(self.labelPreferences)

                # menu container
                self.menu_container = QtWidgets.QHBoxLayout()
                self.menu_container.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
                self.menu_container.setContentsMargins(0, 0, -1, 0)
                self.menu_container.setObjectName("menu_container")
                spacerItem = QtWidgets.QSpacerItem(50, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
                self.menu_container.addItem(spacerItem)
                self.inner_menu_container = QtWidgets.QVBoxLayout()
                self.inner_menu_container.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
                self.inner_menu_container.setContentsMargins(-1, 0, -1, 10)
                self.inner_menu_container.setSpacing(15)
                self.inner_menu_container.setObjectName("inner_menu_container")

                # kingdoms
                self.labelKingdoms = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.labelKingdoms.sizePolicy().hasHeightForWidth())
                self.labelKingdoms.setSizePolicy(sizePolicy)
                self.labelKingdoms.setStyleSheet("\n" "font: 75 18pt \"Ubuntu Condensed\";")
                self.labelKingdoms.setObjectName("labelKingdoms")
                self.inner_menu_container.addWidget(self.labelKingdoms)
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_2.setSpacing(0)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")

                self.checkBox_eukaryota = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
                self.checkBox_eukaryota.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.checkBox_eukaryota.setChecked(True)
                self.checkBox_eukaryota.setObjectName("checkBox_eukaryota")
                self.horizontalLayout_2.addWidget(self.checkBox_eukaryota)

                self.checkBox_bacteria = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
                self.checkBox_bacteria.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.checkBox_bacteria.setChecked(True)
                self.checkBox_bacteria.setObjectName("checkBox_bacteria")
                self.horizontalLayout_2.addWidget(self.checkBox_bacteria)


                self.checkBox_prokaryota = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
                self.checkBox_prokaryota.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.checkBox_prokaryota.setChecked(True)
                self.checkBox_prokaryota.setObjectName("checkBox_prokaryota")
                self.horizontalLayout_2.addWidget(self.checkBox_prokaryota)


                self.checkBox_archaea = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
                self.checkBox_archaea.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.checkBox_archaea.setChecked(True)
                self.checkBox_archaea.setObjectName("checkBox_archaea")
                self.horizontalLayout_2.addWidget(self.checkBox_archaea)


                self.inner_menu_container.addLayout(self.horizontalLayout_2)

                self.container_input_kingdom = QtWidgets.QHBoxLayout()
                self.container_input_kingdom.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
                self.container_input_kingdom.setContentsMargins(10, -1, 40, -1)
                self.container_input_kingdom.setObjectName("container_input_kingdom")
                self.labelinputKingdom = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.labelinputKingdom.sizePolicy().hasHeightForWidth())
                self.labelinputKingdom.setSizePolicy(sizePolicy)
                self.labelinputKingdom.setStyleSheet("")
                self.labelinputKingdom.setObjectName("labelinputKingdom")
                self.container_input_kingdom.addWidget(self.labelinputKingdom)
                self.inputKingdom = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.inputKingdom.sizePolicy().hasHeightForWidth())
                self.inputKingdom.setSizePolicy(sizePolicy)
                self.inputKingdom.setMaximumSize(QtCore.QSize(150, 25))
                self.inputKingdom.setLayoutDirection(QtCore.Qt.LeftToRight)
                self.inputKingdom.setStyleSheet("")
                self.inputKingdom.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.inputKingdom.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.inputKingdom.setObjectName("inputKingdom")
                self.container_input_kingdom.addWidget(self.inputKingdom)
                self.container_input_kingdom.setStretch(0, 1)
                self.container_input_kingdom.setStretch(1, 2)
                self.inner_menu_container.addLayout(self.container_input_kingdom)
                self.labelRegions = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.labelRegions.sizePolicy().hasHeightForWidth())
                self.labelRegions.setSizePolicy(sizePolicy)
                self.labelRegions.setStyleSheet("\n"
        "font: 75 18pt \"Ubuntu Condensed\";")
                self.labelRegions.setObjectName("labelRegions")
                self.inner_menu_container.addWidget(self.labelRegions)
                self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_4.setSpacing(0)
                self.horizontalLayout_4.setObjectName("horizontalLayout_4")
                self.checkBox_rrna = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
                self.checkBox_rrna.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.checkBox_rrna.setChecked(True)
                self.checkBox_rrna.setObjectName("checkBox_rrna")
                self.horizontalLayout_4.addWidget(self.checkBox_rrna)
                self.checkBox_cds = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
                self.checkBox_cds.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.checkBox_cds.setChecked(True)
                self.checkBox_cds.setObjectName("checkBox_cds")
                self.horizontalLayout_4.addWidget(self.checkBox_cds)
                self.checkBox_trna = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
                self.checkBox_trna.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.checkBox_trna.setChecked(True)
                self.checkBox_trna.setObjectName("checkBox_trna")
                self.horizontalLayout_4.addWidget(self.checkBox_trna)
                self.checkBox_centromere = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
                self.checkBox_centromere.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.checkBox_centromere.setChecked(True)
                self.checkBox_centromere.setObjectName("checkBox_centromere")
                self.horizontalLayout_4.addWidget(self.checkBox_centromere)
                self.checkBox_telomere = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
                self.checkBox_telomere.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.checkBox_telomere.setChecked(True)
                self.checkBox_telomere.setObjectName("checkBox_telomere")
                self.horizontalLayout_4.addWidget(self.checkBox_telomere)
                self.inner_menu_container.addLayout(self.horizontalLayout_4)
                self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_5.setSpacing(0)
                self.horizontalLayout_5.setObjectName("horizontalLayout_5")
                self.checkBox_3utr = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
                self.checkBox_3utr.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.checkBox_3utr.setChecked(True)
                self.checkBox_3utr.setObjectName("checkBox_3utr")
                self.horizontalLayout_5.addWidget(self.checkBox_3utr)
                self.checkBox_5utr = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
                self.checkBox_5utr.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.checkBox_5utr.setChecked(True)
                self.checkBox_5utr.setObjectName("checkBox_5utr")
                self.horizontalLayout_5.addWidget(self.checkBox_5utr)
                self.checkBox_mobile_element = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
                self.checkBox_mobile_element.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.checkBox_mobile_element.setChecked(True)
                self.checkBox_mobile_element.setObjectName("checkBox_mobile_element")
                self.horizontalLayout_5.addWidget(self.checkBox_mobile_element)
                self.checkBox_mobile_ncrna = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
                self.checkBox_mobile_ncrna.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.checkBox_mobile_ncrna.setChecked(True)
                self.checkBox_mobile_ncrna.setObjectName("checkBox_mobile_ncrna")
                self.horizontalLayout_5.addWidget(self.checkBox_mobile_ncrna)
                self.checkBox_mobile_intron = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
                self.checkBox_mobile_intron.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.checkBox_mobile_intron.setChecked(True)
                self.checkBox_mobile_intron.setObjectName("checkBox_mobile_intron")
                self.horizontalLayout_5.addWidget(self.checkBox_mobile_intron)
                self.inner_menu_container.addLayout(self.horizontalLayout_5)
                self.container_input_region = QtWidgets.QHBoxLayout()
                self.container_input_region.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
                self.container_input_region.setContentsMargins(10, -1, 40, -1)
                self.container_input_region.setObjectName("container_input_region")
                self.label_inputRegion = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.label_inputRegion.sizePolicy().hasHeightForWidth())
                self.label_inputRegion.setSizePolicy(sizePolicy)
                self.label_inputRegion.setStyleSheet("")
                self.label_inputRegion.setObjectName("label_inputRegion")
                self.container_input_region.addWidget(self.label_inputRegion)
                self.inputRegion = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.inputRegion.sizePolicy().hasHeightForWidth())
                self.inputRegion.setSizePolicy(sizePolicy)
                self.inputRegion.setMaximumSize(QtCore.QSize(150, 25))
                self.inputRegion.setLayoutDirection(QtCore.Qt.LeftToRight)
                self.inputRegion.setStyleSheet("")
                self.inputRegion.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.inputRegion.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.inputRegion.setObjectName("inputRegion")
                self.container_input_region.addWidget(self.inputRegion)
                self.container_input_region.setStretch(0, 1)
                self.container_input_region.setStretch(1, 2)
                self.inner_menu_container.addLayout(self.container_input_region)
                self.menu_container.addLayout(self.inner_menu_container)
                spacerItem1 = QtWidgets.QSpacerItem(50, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
                self.menu_container.addItem(spacerItem1)
                self.menu_container.setStretch(0, 1)
                self.menu_container.setStretch(1, 3)
                self.menu_container.setStretch(2, 1)
                self.right_container.addLayout(self.menu_container)
                self.labelLog = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.labelLog.sizePolicy().hasHeightForWidth())
                self.labelLog.setSizePolicy(sizePolicy)
                self.labelLog.setMinimumSize(QtCore.QSize(0, 0))
                self.labelLog.setStyleSheet("\n"
        "font: 75 20pt \"Ubuntu Mono\";\n"
        "")
                self.labelLog.setAlignment(QtCore.Qt.AlignCenter)
                self.labelLog.setObjectName("labelLog")
                self.right_container.addWidget(self.labelLog)
                self.container_log = QtWidgets.QHBoxLayout()
                self.container_log.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
                self.container_log.setObjectName("container_log")
                self.logTextEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.logTextEdit.sizePolicy().hasHeightForWidth())
                self.logTextEdit.setSizePolicy(sizePolicy)
                self.logTextEdit.setMinimumSize(QtCore.QSize(500, 0))
                self.logTextEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
        "color: rgb(123, 79, 2);")
                self.logTextEdit.setObjectName("logTextEdit")
                self.container_log.addWidget(self.logTextEdit)
                self.right_container.addLayout(self.container_log)
                self.right_container.setStretch(0, 2)
                self.right_container.setStretch(1, 4)
                self.right_container.setStretch(2, 2)
                self.right_container.setStretch(3, 90)
                self.container.addLayout(self.right_container)
                self.container.setStretch(0, 2)
                self.container.setStretch(1, 3)
                self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
                self.graphicsView.setGeometry(QtCore.QRect(20, 110, 451, 641))
                self.graphicsView.setStyleSheet("background-color: rgb(220, 230, 255);")
                self.graphicsView.setObjectName("graphicsView")
                self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
                self.horizontalLayoutWidget.setGeometry(QtCore.QRect(410, 0, 361, 91))
                self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
                self.title_container = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
                self.title_container.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
                self.title_container.setContentsMargins(20, 10, 20, 10)
                self.title_container.setSpacing(0)
                self.title_container.setObjectName("title_container")
                self.mainTitle = QtWidgets.QLabel(self.horizontalLayoutWidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.mainTitle.sizePolicy().hasHeightForWidth())
                self.mainTitle.setSizePolicy(sizePolicy)
                self.mainTitle.setStyleSheet("font: 40pt \"Ubuntu Condensed\";\n"
        "color: rgb(166, 92, 0);")
                self.mainTitle.setAlignment(QtCore.Qt.AlignCenter)
                self.mainTitle.setObjectName("mainTitle")
                self.title_container.addWidget(self.mainTitle)
                self.logo_GView = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.logo_GView.sizePolicy().hasHeightForWidth())
                self.logo_GView.setSizePolicy(sizePolicy)
                self.logo_GView.setObjectName("logo_GView")
                self.title_container.addWidget(self.logo_GView)
                self.title_container.setStretch(0, 3)
                self.title_container.setStretch(1, 1)
                self.mainGraphicView.raise_()
                self.graphicsView.raise_()
                self.horizontalLayoutWidget_2.raise_()
                self.horizontalLayoutWidget.raise_()
                MainWindow.setCentralWidget(self.centralwidget)
                self.Menu = QtWidgets.QMenuBar(MainWindow)
                self.Menu.setGeometry(QtCore.QRect(0, 0, 1173, 22))
                self.Menu.setStyleSheet("")
                self.Menu.setObjectName("Menu")
                self.menuParametres = QtWidgets.QMenu(self.Menu)
                self.menuParametres.setObjectName("menuParametres")
                self.menuChoixKingdoms = QtWidgets.QMenu(self.menuParametres)
                self.menuChoixKingdoms.setObjectName("menuChoixKingdoms")
                self.menuChoixRegions = QtWidgets.QMenu(self.menuParametres)
                self.menuChoixRegions.setObjectName("menuChoixRegions")
                self.menuControles = QtWidgets.QMenu(self.Menu)
                self.menuControles.setObjectName("menuControles")
                MainWindow.setMenuBar(self.Menu)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)
              
                self.actionEucaryota = QtWidgets.QAction(MainWindow)
                self.actionEucaryota.setCheckable(True)
                self.actionEucaryota.setChecked(True)
                self.actionEucaryota.setObjectName("actionEucaryota")
              
                self.actionBacteria = QtWidgets.QAction(MainWindow)
                self.actionBacteria.setCheckable(True)
                self.actionBacteria.setChecked(True)
                self.actionBacteria.setObjectName("actionBacteria")
              
                self.actionArchaea = QtWidgets.QAction(MainWindow)
                self.actionArchaea.setCheckable(True)
                self.actionArchaea.setChecked(True)
                self.actionArchaea.setObjectName("actionArchaea")
             
                self.actionrNA = QtWidgets.QAction(MainWindow)
                self.actionrNA.setCheckable(True)
                self.actionrNA.setChecked(True)
                self.actionrNA.setObjectName("actionrNA")
             
                self.actionCDS = QtWidgets.QAction(MainWindow)
                self.actionCDS.setCheckable(True)
                self.actionCDS.setChecked(True)
                self.actionCDS.setObjectName("actionCDS")
              
                self.actionIntron = QtWidgets.QAction(MainWindow)
                self.actionIntron.setCheckable(True)
                self.actionIntron.setChecked(True)
                self.actionIntron.setObjectName("actionIntron")
               
                self.actionncRNA = QtWidgets.QAction(MainWindow)
                self.actionncRNA.setCheckable(True)
                self.actionncRNA.setChecked(True)
                self.actionncRNA.setObjectName("actionncRNA")
              
                self.actionCentromere = QtWidgets.QAction(MainWindow)
                self.actionCentromere.setCheckable(True)
                self.actionCentromere.setChecked(True)
                self.actionCentromere.setObjectName("actionCentromere")
              
                self.actionTelomere = QtWidgets.QAction(MainWindow)
                self.actionTelomere.setCheckable(True)
                self.actionTelomere.setChecked(True)
                self.actionTelomere.setObjectName("actionTelomere")
              
                self.action3_UTR = QtWidgets.QAction(MainWindow)
                self.action3_UTR.setCheckable(True)
                self.action3_UTR.setChecked(True)
                self.action3_UTR.setObjectName("action3_UTR")
              
                self.action5_UTR = QtWidgets.QAction(MainWindow)
                self.action5_UTR.setCheckable(True)
                self.action5_UTR.setChecked(True)
                self.action5_UTR.setObjectName("action5_UTR")
              
                self.actiontRNA = QtWidgets.QAction(MainWindow)
                self.actiontRNA.setCheckable(True)
                self.actiontRNA.setChecked(True)
                self.actiontRNA.setObjectName("actiontRNA")
              
                self.actionmobile_element = QtWidgets.QAction(MainWindow)
                self.actionmobile_element.setCheckable(True)
                self.actionmobile_element.setChecked(True)
                self.actionmobile_element.setObjectName("actionmobile_element")
              
                self.actionProkaryota = QtWidgets.QAction(MainWindow)
                self.actionProkaryota.setCheckable(True)
                self.actionProkaryota.setChecked(True)
                self.actionProkaryota.setObjectName("actionProkaryota")

                self.actionStart = QtWidgets.QAction(MainWindow)
                self.actionStart.setObjectName("actionStart")
             
                self.actionStop = QtWidgets.QAction(MainWindow)
                self.actionStop.setObjectName("actionStop")
             
                self.actionReprendre = QtWidgets.QAction(MainWindow)
                self.actionReprendre.setObjectName("actionReprendre")
             
                self.actionRedemarrer = QtWidgets.QAction(MainWindow)
                self.actionRedemarrer.setObjectName("actionRedemarrer")
               
                self.menuChoixKingdoms.addAction(self.actionEucaryota)
                self.menuChoixKingdoms.addAction(self.actionBacteria)
                self.menuChoixKingdoms.addAction(self.actionArchaea)
                self.menuChoixKingdoms.addAction(self.actionProkaryota)
               
                self.menuChoixRegions.addAction(self.actionrNA)
                self.menuChoixRegions.addAction(self.actionCDS)
                self.menuChoixRegions.addAction(self.actionIntron)
                self.menuChoixRegions.addAction(self.actionncRNA)
                self.menuChoixRegions.addAction(self.actionCentromere)
                self.menuChoixRegions.addAction(self.actionTelomere)
                self.menuChoixRegions.addAction(self.action3_UTR)
                self.menuChoixRegions.addAction(self.action5_UTR)
                self.menuChoixRegions.addAction(self.actiontRNA)
                self.menuChoixRegions.addAction(self.actionmobile_element)
               
                self.menuParametres.addAction(self.menuChoixKingdoms.menuAction())
                self.menuParametres.addAction(self.menuChoixRegions.menuAction())
               
                self.menuControles.addAction(self.actionStart)
                self.menuControles.addAction(self.actionStop)
                self.menuControles.addAction(self.actionReprendre)
                self.menuControles.addAction(self.actionRedemarrer)
               
                self.Menu.addAction(self.menuControles.menuAction())
                self.Menu.addAction(self.menuParametres.menuAction())

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.labelArborescence.setText(_translate("MainWindow", "Arborescence"))
                self.labelActualise.setText(_translate("MainWindow", "Actualisé"))
                self.labelCree.setText(_translate("MainWindow", "Créé"))
                self.labelSupprime.setText(_translate("MainWindow", "Supprimé"))
                self.buttonStart.setText(_translate("MainWindow", "Start"))
                self.buttonStop.setText(_translate("MainWindow", "Stop"))
                self.buttonReset.setText(_translate("MainWindow", "Reset"))
                self.labelPreferences.setText(_translate("MainWindow", "Préférences"))
                self.labelKingdoms.setText(_translate("MainWindow", "Choix des Kingdoms:"))
                self.checkBox_eukaryota.setText(_translate("MainWindow", "Eukaryota"))
                self.checkBox_bacteria.setText(_translate("MainWindow", "Bacteria"))
                self.checkBox_prokaryota.setText(_translate("MainWindow", "Prokaryota"))
                self.checkBox_archaea.setText(_translate("MainWindow", "Archaea"))
                self.labelinputKingdom.setText(_translate("MainWindow", "Personnalisé:"))
                self.labelRegions.setText(_translate("MainWindow", "Choix des régions fonctionnelles:"))
                self.checkBox_rrna.setText(_translate("MainWindow", "rRna"))
                self.checkBox_cds.setText(_translate("MainWindow", "CDS"))
                self.checkBox_trna.setText(_translate("MainWindow", "tRNA"))
                self.checkBox_centromere.setText(_translate("MainWindow", "Centromère"))
                self.checkBox_telomere.setText(_translate("MainWindow", "Télomère"))
                self.checkBox_3utr.setText(_translate("MainWindow", "3\'UTR"))
                self.checkBox_5utr.setText(_translate("MainWindow", "5\'UTR"))
                self.checkBox_mobile_element.setText(_translate("MainWindow", "Mobile Element"))
                self.checkBox_mobile_ncrna.setText(_translate("MainWindow", "ncRna"))
                self.checkBox_mobile_intron.setText(_translate("MainWindow", "Intron"))
                self.label_inputRegion.setText(_translate("MainWindow", "Personnalisé:"))
                self.labelLog.setText(_translate("MainWindow", "Log"))
                self.logTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
        "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">fzfrfrfr</p></body></html>"))
                self.mainTitle.setText(_translate("MainWindow", "GENBANK"))
                self.menuParametres.setTitle(_translate("MainWindow", "Paramètres"))
                self.menuChoixKingdoms.setTitle(_translate("MainWindow", "Choix des Kingdoms"))
                self.menuChoixRegions.setTitle(_translate("MainWindow", "Choix des régions fonctionnelles"))
                self.menuControles.setTitle(_translate("MainWindow", "Contrôles"))
                self.actionEucaryota.setText(_translate("MainWindow", "Eucaryota"))
                self.actionBacteria.setText(_translate("MainWindow", "Bacteria"))
                self.actionArchaea.setText(_translate("MainWindow", "Archaea"))
                self.actionrNA.setText(_translate("MainWindow", "rRNA"))
                self.actionCDS.setText(_translate("MainWindow", "CDS"))
                self.actionIntron.setText(_translate("MainWindow", "Intron"))
                self.actionncRNA.setText(_translate("MainWindow", "ncRNA"))
                self.actionCentromere.setText(_translate("MainWindow", "Centromère"))
                self.actionTelomere.setText(_translate("MainWindow", "Telomère"))
                self.action3_UTR.setText(_translate("MainWindow", "3\'UTR"))
                self.action5_UTR.setText(_translate("MainWindow", "5\'UTR"))
                self.actiontRNA.setText(_translate("MainWindow", "tRNA"))
                self.actionmobile_element.setText(_translate("MainWindow", "mobile element"))
                self.actionProkaryota.setText(_translate("MainWindow", "Prokaryota"))
                self.actionStart.setText(_translate("MainWindow", "Démarrer"))
                self.actionStop.setText(_translate("MainWindow", "Stop"))
                self.actionReprendre.setText(_translate("MainWindow", "Reprendre"))
                self.actionRedemarrer.setText(_translate("MainWindow", "Redémarrer"))

        def connect_ui(self):
                start = partial(genbank.Genbank.start, self)
                self.buttonStart.clicked.connect(lambda x : start())
                self.buttonStop.clicked.connect(genbank.Genbank.pause)
                self.buttonReset.clicked.connect(genbank.Genbank.reset)
